Develop/add rubocop
StudistCorporation/scimaenaga pull request #5
Opened 2021-11-29 04:17 UTC by kazukishimamoto

## Why?

* Add Rubocop to ensure the quality of your code
* Rubocop is de facto standard for static analysis tools

## What?

* Add rubocop to Gemfile
* Add rules to .rubocop.yml
* Create .rubocop_todo.yml for existing code

## Caveats

When you change the code, please check the `.rubocop_todo.yml` and fix to the code that violates the terms.

2021-11-30 05:42 UTC, kazukishimamoto commented on .rubocop.yml
> +   EnforcedStyle: indented_internal_methods # インデントを許可
コメント消す

2021-11-30 05:43 UTC, kazukishimamoto commented on .rubocop.yml
> +
いらない空白

2021-11-30 05:43 UTC, kazukishimamoto commented on .rubocop.yml
> +
以下duvelを参考にして入れました

2021-11-30 05:52 UTC, valerauko commented on .rubocop_todo.yml
> +# one by one as the offenses are removed from the code base.
これやる予定？

2021-11-30 05:55 UTC, kazukishimamoto commented on .rubocop_todo.yml
> +# one by one as the offenses are removed from the code base.
変更があったときに、そのファイル内の修正も合わせてやる感じで考えてます

2021-11-30 06:19 UTC, valerauko commented on .rubocop_todo.yml
> +# one by one as the offenses are removed from the code base.
こいつら意識することは絶対ないから、このファイルなしにしてファイル編集したら言われるようにすればいいじゃないかな。

2021-11-30 08:32 UTC, kazukishimamoto commented on .rubocop_todo.yml
> +# one by one as the offenses are removed from the code base.
確かにそうですねw
こんなのあるんだーと思って作ってみたんですが、ファイル編集したら言われるのほうが良さそうです

2021-11-30 09:31 UTC, valerauko requested changes

2021-11-30 09:31 UTC, valerauko commented on .rubocop.yml
> +Style/ClassAndModuleChildren:
このルールあるんだ... 調べないと何なのかわからなかった

別に消す必要ないと思うけど、このプロジェクトで多く違反があったかな？

2021-11-30 09:31 UTC, valerauko commented on .rubocop.yml
> +Layout/EmptyLineAfterGuardClause:
これわかりやすいし有効にしちゃってもいいかも

2021-11-30 09:31 UTC, valerauko commented on .rubocop.yml
> +    - "config/initializers/constants/*"
コピペがすぎるｗ

このいずれもこのプロジェクトに存在しないので不要

2021-11-30 09:31 UTC, valerauko commented on .rubocop.yml
> +    - 'config/initializers/*.rb'
ないので不要

2021-12-01 02:44 UTC, kazukishimamoto commented on .rubocop.yml
> +Style/ClassAndModuleChildren:
> このプロジェクトで多く違反があったかな？

ざっと見た感じ違反なさそうでした！

2021-12-01 02:48 UTC, kazukishimamoto commented
不要箇所が多くて失礼しました。pathをチェックして削除しました

2021-12-01 02:51 UTC, kazukishimamoto commented on .rubocop.yml
> +Layout/EmptyLineAfterGuardClause:
Guard句の後に改行いれるやつですね。
確かにあるとわかりやすそうなので有効にしてみます。
細かい精査できてなかったのでレビュー助かりました

2021-12-01 06:41 UTC, valerauko commented on .rubocop.yml
> +    - 'config/routes/*.rb'
これはないよ

2021-12-02 02:58 UTC, kazukishimamoto commented on .rubocop.yml
> +    - 'spec/**/**/*.rb'
spec/dummy/以下の指定は不要と判断して、`'spec/**/**/*.rb'`の深さまでにする

2021-12-02 02:58 UTC, kazukishimamoto reviewed
全部のルールみて不要そうなものはなかったし、Metrics/BlockLengthのpathも精査しました

2021-12-02 03:50 UTC, m0sh1dawa approved these changes

2021-12-02 04:31 UTC, valerauko approved these changes

2021-12-02 05:00 UTC, merged