Support 3.3.x (x != 0)
StudistCorporation/scimaenaga pull request #52
Opened 2024-06-13 08:41 UTC by znz

## Why?

`<= 3.3` means `<= 3.3.0`, so this cannot install with 3.3.1 or later.

```
scimaenaga-1.0.2 requires ruby version >= 2.5.9, <= 3.3, which is incompatible
with the current version, ruby 3.3.3p89
```

## What?

`< 3.4` supports 3.3.x (x != 0) too.

## Caveats

Nothing affects already supported versions.

2024-06-13 09:02 UTC, valerauko requested changes
Thanks for the contribution!

2024-06-13 09:02 UTC, valerauko commented on scimaenaga.gemspec
> -  s.required_ruby_version = '>= 2.5.9', '<= 3.3'
Please add your problematic version (3.3.3?) to the test matrix after 3.3.0 at https://github.com/StudistCorporation/scimaenaga/blob/5d90e9e99a65ed60d457470ad510b51374ce3fc0/.github/workflows/test.yaml#L58

2024-06-13 09:10 UTC, mtakeda15 commented
@znz 
I want to keep updating test.yml when new ruby version is released, so I prefer `<= 3.3.3` to `<3.4`.

2024-06-18 09:54 UTC, mtakeda15 approved these changes
Thank you for your contribution!!

2024-06-18 09:58 UTC, valerauko approved these changes

2024-06-18 10:01 UTC, merged